name: "ci: Terraform CI/CD via OIDC (plan PR / apply main)"

on:
  push:
    paths:
      - '**.tf'
      - '.github/workflows/deploy.yml'
      - 'modules/**'
      - 'site/**'
  pull_request:
    paths:
      - '**.tf'
      - '.github/workflows/deploy.yml'
      - 'modules/**'
      - 'site/**'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::728182301123:role/GitHubActionsOIDCFullstackTerraform
          aws-region: ${{ env.AWS_REGION }}

      # 👉 preuve que l’assume-role marche
      - name: Who am I in AWS?
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      # 👉 ne bloque plus le run si des diffs de formatage existent
      - name: Terraform fmt (non blocking)
        run: terraform fmt -check -recursive || echo "::warning ::fmt found differences (ignored)"

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        if: github.event_name == 'pull_request' || github.ref != 'refs/heads/main'
        run: terraform plan -input=false -no-color

      - name: Terraform apply (main only)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false -no-color
