name: ci: Terraform CI/CD via OIDC (plan PR / apply main)

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/deploy.yml"
      - "**/*.tf"
      - "modules/**"
      - "site/**"
  pull_request:
    branches: [ main ]
    paths:
      - "**/*.tf"
      - "modules/**"

permissions:
  id-token: write   # OIDC
  contents: read    # checkout

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::728182301123:role/GitHubActionsOIDCFullstackTerraform
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform fmt
        run: terraform fmt -check -recursive || true

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -no-color -input=false -out=tfplan

      # Apply uniquement sur main (pas sur PR)
      - name: Terraform apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false tfplan
